#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : litehtml
Version  : 0.5
Release  : 1
URL      : file:///insilications/build/clearlinux/packages/litehtml/litehtml-v0.5.tar.gz
Source0  : file:///insilications/build/clearlinux/packages/litehtml/litehtml-v0.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : buildreq-cmake
BuildRequires : gvim
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![Travis Build Status](https://travis-ci.org/litehtml/litehtml.svg?branch=master)](https://travis-ci.org/litehtml/litehtml)

%package dev
Summary: dev components for the litehtml package.
Group: Development
Provides: litehtml-devel = %{version}-%{release}
Requires: litehtml = %{version}-%{release}

%description dev
dev components for the litehtml package.


%prep
%setup -q -n litehtml
cd %{_builddir}/litehtml

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1609500222
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
export CFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
# -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fpic -fvisibility=hidden -flto-partition=none
# gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common
export CXXFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC"
#
export FCFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
export FFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
export CFFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
#
export LDFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
#
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
#
unset CCACHE_DISABLE
export PATH="/usr/lib64/ccache/bin:$PATH"
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
## altflags1 end
%cmake .. -DCMAKE_BUILD_TYPE=Release \
-DLITEHTML_UTF8=ON
make  %{?_smp_mflags}  V=1 VERBOSE=1
## ccache stats
ccache -s
## ccache stats
popd

%install
export SOURCE_DATE_EPOCH=1609500222
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/gumbo/attribute.h
/usr/include/gumbo/char_ref.h
/usr/include/gumbo/error.h
/usr/include/gumbo/gumbo.h
/usr/include/gumbo/insertion_mode.h
/usr/include/gumbo/parser.h
/usr/include/gumbo/string_buffer.h
/usr/include/gumbo/string_piece.h
/usr/include/gumbo/tag_enum.h
/usr/include/gumbo/tag_gperf.h
/usr/include/gumbo/tag_sizes.h
/usr/include/gumbo/tag_strings.h
/usr/include/gumbo/token_type.h
/usr/include/gumbo/tokenizer.h
/usr/include/gumbo/tokenizer_states.h
/usr/include/gumbo/utf8.h
/usr/include/gumbo/util.h
/usr/include/gumbo/vector.h
/usr/include/litehtml/attributes.h
/usr/include/litehtml/background.h
/usr/include/litehtml/borders.h
/usr/include/litehtml/box.h
/usr/include/litehtml/context.h
/usr/include/litehtml/css_length.h
/usr/include/litehtml/css_margins.h
/usr/include/litehtml/css_offsets.h
/usr/include/litehtml/css_position.h
/usr/include/litehtml/css_selector.h
/usr/include/litehtml/document.h
/usr/include/litehtml/el_anchor.h
/usr/include/litehtml/el_base.h
/usr/include/litehtml/el_before_after.h
/usr/include/litehtml/el_body.h
/usr/include/litehtml/el_break.h
/usr/include/litehtml/el_cdata.h
/usr/include/litehtml/el_comment.h
/usr/include/litehtml/el_div.h
/usr/include/litehtml/el_font.h
/usr/include/litehtml/el_image.h
/usr/include/litehtml/el_link.h
/usr/include/litehtml/el_para.h
/usr/include/litehtml/el_script.h
/usr/include/litehtml/el_space.h
/usr/include/litehtml/el_style.h
/usr/include/litehtml/el_table.h
/usr/include/litehtml/el_td.h
/usr/include/litehtml/el_text.h
/usr/include/litehtml/el_title.h
/usr/include/litehtml/el_tr.h
/usr/include/litehtml/element.h
/usr/include/litehtml/html.h
/usr/include/litehtml/html_tag.h
/usr/include/litehtml/iterators.h
/usr/include/litehtml/litehtml.h
/usr/include/litehtml/media_query.h
/usr/include/litehtml/num_cvt.h
/usr/include/litehtml/os_types.h
/usr/include/litehtml/style.h
/usr/include/litehtml/stylesheet.h
/usr/include/litehtml/table.h
/usr/include/litehtml/types.h
/usr/include/litehtml/utf8_strings.h
/usr/include/litehtml/web_color.h
/usr/lib/cmake/gumbo/gumboConfig-release.cmake
/usr/lib/cmake/gumbo/gumboConfig.cmake
/usr/lib/cmake/litehtml/litehtmlConfig.cmake
/usr/lib/cmake/litehtml/litehtmlTargets-release.cmake
/usr/lib/cmake/litehtml/litehtmlTargets.cmake
/usr/lib64/libgumbo.so
/usr/lib64/liblitehtml.so
